version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10 # the primary container, where your job's commands are run
    branches: # 告诉ci服务器要去去拉取master分支
      only:
        - master
    steps:
      - add_ssh_keys: # 告诉github我用什么密钥去与你通讯
          fingerprints:
            - "6b:43:ad:35:dc:5a:8a:9f:75:c6:15:0c:06:d6:d1:40" # 这里需要在ci里配置user key
      - checkout # 去拉取这个分支
      - restore_cache: # 有，就恢复缓存文件
          key: dependences-simens
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependences-simens   # 保存一个key值为。。。的缓存文件
          paths:
            - node_modules         # 指定需要被缓存的文件夹
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prepare shell commands
          # shell chmod +x 赋予执行权限
          command: chmod +x script/deploy.sh
      - run:
          name: Run Deploy to Github pages
          # 执行shell脚本,注意需要在ci平台对应项目的设置里设置于shell脚本对应的环境变量
          command:  ./script/deploy.sh
